config/routes.rb
Infosystem::Application.routes.draw do

  devise_for :members

  resources :members do
    collection do
      get :search
      post :search
      get :all
    end
    resources :subscriptions, :controller => :subscriptions, :only => [:index, :create, :destroy] do
      collection do
        get :change
      end
    end
    resources :membership_fees, :only => [:index, :new, :create, :destroy]
    resources :sections, :controller => "member_sections", :only => [:index]
    resources :projects, :controller => "member_projects", :only => [:index]
    resources :fieldworks, :controller => "member_fieldworks", :only => [:index]
  end

  resources :sections do
    collection do
      get :search
      post :search
    end
    resources :memberships, :controller => "section_memberships", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resources :reports, :controller => "section_reports", :except => [:edit, :update, :show] do
      member do
        get :upload
        get :download
      end
    end
  end

  resources :projects do
    collection do
      get :search
      post :search
    end
    resources :participations, :controller => "project_participations", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resource :report, :controller => "project_reports", :except => [:index, :edit, :update] do
      member do
        get :download
      end
    end
  end

  resources :fieldworks do
    collection do
      get :search
      post :search
    end
    resources :participations, :controller => "fieldwork_participations", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resource :report, :controller => "fieldwork_reports", :except => [:index, :edit, :update] do
      member do
        get :download
      end
    end
  end

  resources :letters do
    member do
      get :download
    end
    collection do
      get :incoming
      get :outgoing
      get :search
      post :search
    end
  end

  resources :transfers do
    collection do 
      get :secret
      get :incoming
      get :outgoing
      get :search
      post :search
    end
  end

  resources :items do
    collection do
      get :loans
      get :search
      post :search
    end
    resources :loans, :controller => "item_loans"
  end

  resources :books do
    collection do
      get :loans
      get :search
      post :search
    end
    resources :loans, :controller => "book_loans"
  end

  resources :notifications do
    collection do
      get :search
      get :relevant
      get :send
    end
  end

  resources :tags do
    collection do
      get :search
      get :generate
    end
  end

  resource :user, :controller => "user" do
    member do
      get 'login'
      get 'logout'
    end
  end
  
  root :to => "members#index"

end

app/controllers/book_loans_controller.rb
class BookLoansController < ApplicationController
  load_and_authorize_resource

  def index
    @book = Book.find(params[:book_id])
    if @book.loans.empty?
      flash[:notice] = "No book loans."
    end
  end

  def history
    @book = Book.find(params[:id])
    if @book.loans.empty?
      flash[:notice] = "No book history."
    end
  end

  def new
    @book = Book.find(params[:book_id])
    @loan = Loan.new
    @members = Member.members.sort! {|x, y| x.name <=> y.name}
  end

  def create
    @book = Book.find(params[:book_id])
    @book.loans << Loan.new(params[:loan])
    if @book.save
      flash.now[:notice] = "Book loan was successfully created."
      redirect_to book_loans_url(@book)
    else
      render new_book_loan_url(@book)
    end
  end

  def edit
    @book = Book.find(params[:book_id])
    @loan = Loan.find(params[:id])
    @members = Member.members.sort! {|x, y| x.name <=> y.name}
  end

  def update
    @book = Book.find(params[:book_id])
    @loan = Loan.find(params[:id])
    if @loan.update_attributes(params[:loan])
      flash.now[:notice] = "Book loan was successfully created."
      redirect_to book_loans_url(@book)
    else
      render new_book_loan(@book)
    end
  end

  def destroy
    @loan = Loan.find(params[:id])
    if @loan.destroy
      flash[:notice] = "Loan was successfully deleted."
      redirect_to book_loans_url(@book)
    end
  end

end

app/views/book_loans/_show_menu.html.erb
<%= link_to 'Index', books_url %> |
<%= link_to 'Info', book_url(@book) %> |
<%= link_to 'Edit', edit_book_url(@book) %> |
<%= link_to 'Destroy', book_url(@book), :method => :delete, :confirm => "Are you sure?" %> |
<%= link_to 'Loans', book_loans_url(@book) %>
<hr/>

app/views/book_loans/edit.html.erb
<% content_for :head do %> 
<%= render :partial => "books/show_menu" %>
<% end %>

<%= error_messages_for :loan %>

<%= form_for [@book, @loan] do |f| %>

<%= render_form('loans/form', f) %>

<p> <%= f.submit 'Update' %> </p>

<% end %>

app/views/book_loans/index.html.erb
<% content_for :head do %> 
<%= render :partial => "books/show_menu" %>
<% end %>

<% unless @book.loans.empty? %>
<ul>
  <% for l in @book.loans %>
  <li>
  <%= link_to "[x]", book_loan_url(@book, l), :method => :delete %> |
  Posudio: <%= link_to l.borrower.name, member_url(l.borrower) %> | 
  Odobrio: <%= link_to l.lender.name, member_url(l.lender) %> | 
  Datum posudbe: <%= link_to l.date_from, edit_book_loan_url(@book, l) %> | 
  Datum povratka: <%= link_to l.date_to, edit_book_loan_url(@book, l) if l.date_to %>
  </li>
  <% end %>
</ul>
<% end %>

<%= link_to 'New', new_book_loan_url(@book) %>

app/views/book_loans/new.html.erb
<% content_for :head do %> 
<%= render :partial => "books/show_menu" %>
<% end %>

<%= error_messages_for :loan %>

<%= form_for [@book, @loan] do |f| %>

<%= render_form('loans/form', f) %>

<p> <%= f.submit 'Create' %> </p>

<% end %>