config/routes.rb
Infosystem::Application.routes.draw do

  devise_for :members

  resources :members do
    collection do
      get :search
      post :search
      get :all
    end
    resources :subscriptions, :controller => :subscriptions, :only => [:index, :create, :destroy] do
      collection do
        get :change
      end
    end
    resources :membership_fees, :only => [:index, :new, :create, :destroy]
    resources :sections, :controller => "member_sections", :only => [:index]
    resources :projects, :controller => "member_projects", :only => [:index]
    resources :fieldworks, :controller => "member_fieldworks", :only => [:index]
  end

  resources :sections do
    collection do
      get :search
      post :search
    end
    resources :memberships, :controller => "section_memberships", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resources :reports, :controller => "section_reports", :except => [:edit, :update, :show] do
      member do
        get :upload
        get :download
      end
    end
  end

  resources :projects do
    collection do
      get :search
      post :search
    end
    resources :participations, :controller => "project_participations", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resource :report, :controller => "project_reports", :except => [:index, :edit, :update] do
      member do
        get :download
      end
    end
  end

  resources :fieldworks do
    collection do
      get :search
      post :search
    end
    resources :participations, :controller => "fieldwork_participations", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resource :report, :controller => "fieldwork_reports", :except => [:index, :edit, :update] do
      member do
        get :download
      end
    end
  end

  resources :letters do
    member do
      get :download
    end
    collection do
      get :incoming
      get :outgoing
      get :search
      post :search
    end
  end

  resources :transfers do
    collection do 
      get :secret
      get :incoming
      get :outgoing
      get :search
      post :search
    end
  end

  resources :items do
    collection do
      get :loans
      get :search
      post :search
    end
    resources :loans, :controller => "item_loans"
  end

  resources :books do
    collection do
      get :loans
      get :search
      post :search
    end
    resources :loans, :controller => "book_loans"
  end

  resources :notifications do
    collection do
      get :search
      get :relevant
      get :send
    end
  end

  resources :tags do
    collection do
      get :search
      get :generate
    end
  end

  resource :user, :controller => "user" do
    member do
      get 'login'
      get 'logout'
    end
  end
  
  root :to => "members#index"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	has_and_belongs_to_many :tags
	validates_presence_of :title
	validates_presence_of :body
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = Notification.all
    if @notifications.empty?
      flash[:notice] = "No notifications to show."
    end
    respond_to do |format|
      format.html
      format.xml { render :xml => @notifications.to_xml }
    end
  end

  def relevant
    @member = Member.find(session[:user_id])
    @notifications = @member.tags.collect {|t| t.notifications}.flatten!
    if @member.tags.empty? or @notifications.empty?
      @notifications = []
      flash[:notice] = "No relevant notifications to show."
    end
    respond_to do |format|
      format.html { render 'index' }
      format.xml { render :xml => @notifications.to_xml }
    end
  end

  def search
    @notifications = []
    if params[:keyword]
      params[:keyword] = '%' + params[:keyword] + '%'
      @notifications = Notification.where(["title ILIKE ?" , params[:keyword]])
      if @notifications.empty?
        flash[:notice] = "No such notifications in database."
      end
    end
  end

  def show
    @notification = Notification.find(params[:id])
  end

  def new
    @notification = Notification.new
    @tags = Tag.all
    if @tags.empty?
      flash.now[:tags] = "No tags in database."
    end
  end

  def edit
    @notification = Notification.find(params[:id])
    @tags = Tag.all
    if @tags.empty?
      flash.now[:tags] = "No tags in database."
    end
  end

  def create
    @tags = Tag.all
    @notification = Notification.new(params[:notification])
    @notification.sent = false
    @notification.tag_ids = params[:tag_ids] if params[:tag_ids]
    if @notification.save
      flash.now[:notice] = "Notification was successfully created."
      redirect_to :action => 'index'
    else
      render "new"
    end
  end

  def update
    @notification = Notification.find(params[:id])
    @notification.tag_ids = params[:tag_ids] if params[:tag_ids]
    @notification.sent = false
    if @notification.update_attributes(params[:notification])
      flash[:notice] = "Notification was successfully updated."
      redirect_to :action => 'index'
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    if @notification.destroy
      flash[:notice] = 'Notification was successfully deleted.'
      redirect_to :action => 'index'
    end
  end

  def mail
    test_string = ""
    @notifications = Notification.all(:conditions => {:sent => false})
    @notifications.each do |n|
      n.toggle(:sent)
      n.save
      recipients = n.tags.collect {|t| t.members}.flatten!
      #email =
      InfoMailer.deliver_notification(subject = "notification", body = n.body, recipients = recipients)
      #test_string += "<pre>" + email.encoded + "</pre><hr/>"
    end
    #render(:text => test_string)
    unless @notifications.empty?
      flash[:notice] = "Notifications sent."
    else
      flash[:notice] = "All notifications previously sent."
    end
    redirect_to notifications_url
  end

end

app/views/notifications/_index_menu.html.erb
<%= link_to 'Index', notifications_url %> | 
<%= link_to 'New', new_notification_url %> | 
<%= link_to 'Search', search_notifications_url %>

app/views/notifications/_show_menu.html.erb
<%= link_to 'Index', notifications_url %> |
<%= link_to 'Info', notification_url(@notification) %> | 
<%= link_to 'Edit', edit_notification_url(@notification) %> | 
<%= link_to 'Destroy', notification_url(@notification), :method => :delete, :confirm => "Are you sure?" %>

app/views/notifications/_sub_menu.html.erb
<%= link_to 'Relevant', relevant_notifications_url %> | 
<%= link_to 'All', notifications_url %>

app/views/notifications/edit.html.erb
<% content_for :head do %> 
<%= render :partial => "show_menu" %>
<% end %>

<%= error_messages_for :notification %>

<% form_for @notification , edit_notification_url do |form| %>

<p>
Title:<br/>
<%= form.text_field :title %>
</p>

<p>
Body:<br/>
<%= form.text_area :body, :rows => '10', :cols => '30' %>
</p>

<p>
Tags: |
<% for tag in @tags %>
 <%= tag.title %>
 <%= check_box_tag 'tag_ids[]', tag.id , @notification.tag_ids.include?(tag.id) %> |
<% end %>
</p>

<p>
<%= submit_tag 'Update' %>
</p>

<% end %>

app/views/notifications/index.html.erb
<% content_for :head do %> 
<%= render :partial => "index_menu" %> : <%= render :partial => "sub_menu" %>
<% end %>

<% unless @notifications.empty? %>

<% for notification in @notifications %>
<p> <%= link_to notification.title, notification_url(notification) %>  </p>
<p> <%= notification.body %> </p>
<hr/>
<% end %>

<% end %>

app/views/notifications/new.html.erb
<% content_for :head do %> 
<%= render :partial => "index_menu" %>
<% end %>

<%= error_messages_for :notification %>

<% form_for @notification , new_notification_url do |form| %>

<p>
Title:<br/>
<%= form.text_field :title %>
</p>

<p>
Body:<br/>
<%= form.text_area :body, :rows => '10', :cols => '30' %>
</p>

<% unless @tags.empty? %>
<p>
Tags: <br/>
<% for tag in @tags %>
 <%= tag.title %> <%= check_box_tag('tag_ids[]', tag.id) %> |
<% end %>
</p>

<% else %>
<%= flash[:tags] %>

<% end %>
<p>
<%= submit_tag 'Create' %>
</p>

<% end %>

app/views/notifications/search.html.erb
<% content_for :head do %> 
  <%= render :partial => "index_menu" %>
<% end %>

<%= form_tag search_notifications_path do %>
  <div>
    Naslov...<br/>
    <%= text_field_tag 'keyword' %>
    <%= submit_tag "Search" %>
  </div>
<% end %>


<% unless @notifications.empty? %>
  <div>
    <table border='1'>

      <tr>
        <th>Title</th>
        <th>Body</th></tr>

      <% for notification in @notifications %>
        <tr>
          <td><%= link_to notification.title, notification_url(notification) %></td>
          <td><%=h notification.body %></td>
        </tr>
      <% end %>

    </table>
  </div>
<% end %>

app/views/notifications/show.html.erb
<% content_for :head do %> 
<%= render :partial => "show_menu" %>
<% end %>

Naslov: <%= @notification.title %><br/>

Tijelo: <%= @notification.body %><br/>

Tegovi: 
<% for tag in @notification.tags %>
<%= tag.title %></br>
<% end %>