config/routes.rb
Infosystem::Application.routes.draw do

  devise_for :members

  resources :members do
    collection do
      get :search
      post :search
      get :all
    end
    resources :subscriptions, :controller => :subscriptions, :only => [:index, :create, :destroy] do
      collection do
        get :change
      end
    end
    resources :membership_fees, :only => [:index, :new, :create, :destroy]
    resources :sections, :controller => "member_sections", :only => [:index]
    resources :projects, :controller => "member_projects", :only => [:index]
    resources :fieldworks, :controller => "member_fieldworks", :only => [:index]
  end

  resources :sections do
    collection do
      get :search
      post :search
    end
    resources :memberships, :controller => "section_memberships", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resources :reports, :controller => "section_reports", :except => [:edit, :update, :show] do
      member do
        get :upload
        get :download
      end
    end
  end

  resources :projects do
    collection do
      get :search
      post :search
    end
    resources :participations, :controller => "project_participations", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resource :report, :controller => "project_reports", :except => [:index, :edit, :update] do
      member do
        get :download
      end
    end
  end

  resources :fieldworks do
    collection do
      get :search
      post :search
    end
    resources :participations, :controller => "fieldwork_participations", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resource :report, :controller => "fieldwork_reports", :except => [:index, :edit, :update] do
      member do
        get :download
      end
    end
  end

  resources :letters do
    member do
      get :download
    end
    collection do
      get :incoming
      get :outgoing
      get :search
      post :search
    end
  end

  resources :transfers do
    collection do 
      get :secret
      get :incoming
      get :outgoing
      get :search
      post :search
    end
  end

  resources :items do
    collection do
      get :loans
      get :search
      post :search
    end
    resources :loans, :controller => "item_loans"
  end

  resources :books do
    collection do
      get :loans
      get :search
      post :search
    end
    resources :loans, :controller => "book_loans"
  end

  resources :notifications do
    collection do
      get :search
      get :relevant
      get :send
    end
  end

  resources :tags do
    collection do
      get :search
      get :generate
    end
  end

  resource :user, :controller => "user" do
    member do
      get 'login'
      get 'logout'
    end
  end
  
  root :to => "members#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_participations, :dependent => :destroy
  has_many :members, :through => :project_participations
  has_many :leaders, :through => :project_participations, :source => 'member' , :conditions => "project_participations.role = 'leader'"
  has_many :participants, :through => :project_participations, :source => 'member' , :conditions => "project_participations.role = 'participant'"
  has_one :report, :as => :reportable, :dependent => :delete
  has_and_belongs_to_many :items, :join_table => "items_projects"

  validates_presence_of :title
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @projects = Project.all
    if @projects.empty?
      flash[:notice] = "No projects in database."
    end
    respond_to do |format|
      format.html
      format.xml { render :xml => @projects.to_xml }
    end
  end

  def search
    @projects = []
    if params[:keyword]
      params[:keyword] = '%' + params[:keyword] + '%'
      @projects = Project.where(["title ILIKE ?" , params[:keyword]])
      if @projects.empty?
        flash[:notice] = "No such projects in database."
      end
    end
  end

  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html # index.rhtml
      format.xml { render :xml => @project.to_xml }
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project was successfully created."
      redirect_to projects_url
    else
      render "new"
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project was successfully updated."
      redirect_to project_url(@project)
    else
      render "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:notice] = "Project was successfully deleted."
      redirect_to :action => 'index'
    end
  end

  def list
    @member = Member.find(params[:member_id])
    @projects = @member.projects_as_leader + @member.projects_as_participant
  end

end

app/views/projects/_form.html.erb
<div>
  Naziv:<br/>
  <%= f.text_field :title %>
</div>

<div>
  Svrha:<br/>
  <%= f.text_area :purpose , :rows => '10' , :cols => '30' %>
</div>

<div>
  Godina:<br/>
  <%= f.text_field :year, :size => '5' %>
</div>

<div>
  Izvrsenje:<br/>
  <%= f.text_field :execution %>
</div>

<div>
  Suradnje:<br/>
  <%= f.text_area :cooperations , :rows => '10' , :cols => '20' %>
</div>

<div>
  Priznanja:<br/>
  <%= f.text_area :purpose , :rows => '10' , :cols => '20' %>
</div>

app/views/projects/_index_menu.html.erb
<%= link_to 'Index', projects_url %> | 
<%= link_to 'New', new_project_url %> | 
<%= link_to 'Search', search_projects_url %>

app/views/projects/_show_menu.html.erb
<%= link_to 'Index', projects_url %> |
<%= link_to 'Info', project_url(@project) %> |
<%= link_to 'Edit', edit_project_url(@project) %> |
<%= link_to 'Destroy', project_url(@project), :method => :delete, :confirm=>"Are you sure?" %> |
<%= link_to 'Participations', project_participations_url(@project) %> |
<%= link_to 'Registrations', registrations_project_participations_url(@project) %> |
<%= link_to 'Report', project_report_url(@project) %>

app/views/projects/edit.html.erb
<% content_for :head do %> 
<%= render :partial => "show_menu" %>
<% end %>

<%= error_messages_for :project %>

<%= form_for @project do |f| %>

<%= render_form('form', f) %>

<p><%= f.submit "Update" %></p>
  
<% end %>

app/views/projects/index.html.erb
<% content_for :head do %> 
<%= render :partial => "index_menu" %>
<% end %>

<% unless @projects.empty? %>
<p>
<ul>

<% for project in @projects %>
<li><%= link_to project.title, project_url(project) %></li>
<% end %>

</ul>
</p>
<% end %>

app/views/projects/new.html.erb
<% content_for :head do %> 
  <%= render :partial => "index_menu" %>
<% end %>

<%= error_messages_for :project %>

<%= form_for @project do |f| %>

  <%= render_form('form', f) %>

  <div>
    <%= f.submit "Create" %>
  </div>

<% end %>

app/views/projects/search.html.erb
<% content_for :head do %> 
  <%= render :partial => "index_menu" %>
<% end %>

<%= form_tag search_projects_path do %>
  <div>
    Naziv...<br/>
    <%= text_field_tag 'keyword' %>
    <%= submit_tag "Search" %>
  </div>
<% end %>


<% unless @projects.empty? %>
  <div>
    <ul>
      <% for project in @projects %>
        <li><%= link_to project.title, project_url(project) %></li>
      <% end %>
    </div>
  </ul>
<% end %>

app/views/projects/show.html.erb
<% content_for :head do %> 
<%= render :partial => "show_menu" %>
<% end %>

<p>Naziv: <%= @project.title %></p>

<p>
Svrha:<br/>
<%= @project.purpose %>
</p>

<p>Godina: <%= @project.year %></p>

<p>Izvrsitelj: <%= @project.execution %></p>

<p>
Suradnje:<br/>
<%= @project.cooperations %>
</p>

<p>
Priznanja:<br/>
<%= @project.recognitios %>
</p>