config/routes.rb
Infosystem::Application.routes.draw do

  devise_for :members

  resources :members do
    collection do
      get :search
      post :search
      get :all
    end
    resources :subscriptions, :controller => :subscriptions, :only => [:index, :create, :destroy] do
      collection do
        get :change
      end
    end
    resources :membership_fees, :only => [:index, :new, :create, :destroy]
    resources :sections, :controller => "member_sections", :only => [:index]
    resources :projects, :controller => "member_projects", :only => [:index]
    resources :fieldworks, :controller => "member_fieldworks", :only => [:index]
  end

  resources :sections do
    collection do
      get :search
      post :search
    end
    resources :memberships, :controller => "section_memberships", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resources :reports, :controller => "section_reports", :except => [:edit, :update, :show] do
      member do
        get :upload
        get :download
      end
    end
  end

  resources :projects do
    collection do
      get :search
      post :search
    end
    resources :participations, :controller => "project_participations", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resource :report, :controller => "project_reports", :except => [:index, :edit, :update] do
      member do
        get :download
      end
    end
  end

  resources :fieldworks do
    collection do
      get :search
      post :search
    end
    resources :participations, :controller => "fieldwork_participations", :except => [:edit, :show] do
      collection do
        get :apply
        get :registrations
      end
    end
    resource :report, :controller => "fieldwork_reports", :except => [:index, :edit, :update] do
      member do
        get :download
      end
    end
  end

  resources :letters do
    member do
      get :download
    end
    collection do
      get :incoming
      get :outgoing
      get :search
      post :search
    end
  end

  resources :transfers do
    collection do 
      get :secret
      get :incoming
      get :outgoing
      get :search
      post :search
    end
  end

  resources :items do
    collection do
      get :loans
      get :search
      post :search
    end
    resources :loans, :controller => "item_loans"
  end

  resources :books do
    collection do
      get :loans
      get :search
      post :search
    end
    resources :loans, :controller => "book_loans"
  end

  resources :notifications do
    collection do
      get :search
      get :relevant
      get :send
    end
  end

  resources :tags do
    collection do
      get :search
      get :generate
    end
  end

  resource :user, :controller => "user" do
    member do
      get 'login'
      get 'logout'
    end
  end
  
  root :to => "members#index"

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  # To avoid STI
  TYPE = {:incoming => 'i', :outgoing => 'o'}

  belongs_to :member
  
  validates_presence_of :in_out
  validates_presence_of :amount
  validates_numericality_of :amount
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  load_and_authorize_resource

  def index
    @transfers = Transfer.all
    if @transfers.empty?
      flash.now[:notice] = "No transfers in database."
    end

    respond_to do |format|
      format.html
      format.xml { render :xml => @transfers.to_xml }
    end
  end

  def search
    @transfers = []
    if params[:keyword]
      params[:keyword] = '%' + params[:keyword] + '%'
      @transfers = Transfer.where(["purpose ILIKE ?" , params[:keyword]])
      if @transfers.empty?
        flash[:notice] = "messages.transfers.search.empty"
      end
      respond_to do |format|
        format.html
        format.xml { render :xml => @transfers.to_xml }
        format.json { render :json => @transfers.to_json }
      end
    end
  end

  def secret
    @transfers = Transfer.all(:conditions => {:is_secret => true})
    if @transfers.empty?
      flash.now[:notice] = "No such transfers in database."
    end

    respond_to do |format|
      format.html { render "index" }
      format.xml { render :xml => @transfers.to_xml }
    end
  end

  def incoming
    @transfers = Transfer.all(:conditions => {:in_out => Transfer::TYPE[:incoming]})
    if @transfers.empty?
      flash.now[:notice] = "No such transfers in database."
    end

    respond_to do |format|
      format.html { render "index" }
      format.xml { render :xml => @transfers.to_xml }
    end
  end

  def outgoing
    @transfers = Transfer.all(:conditions => {:in_out => Transfer::TYPE[:outgoing]})
    if @transfers.empty?
      flash.now[:notice] = "No such transfers in database."
    end

    respond_to do |format|
      format.html { render "index" }
      format.xml { render :xml => @transfers.to_xml }
    end
  end

  def show
    @transfer = Transfer.find(params[:id])
  end

  def new
    @transfer = Transfer.new
  end

  def create
    @transfer = Transfer.new(params[:transfer])
    if @transfer.save
      flash.now[:notice] = "Transfer was successfully created."
      redirect_to transfers_url
    else
      render "new"
    end
  end

  def edit
    @transfer = Transfer.find(params[:id])
  end

  def update
    @transfer = Transfer.find(params[:id])
    if @transfer.update_attributes(params[:transfer])
      flash.now[:notice] = "Transfer was successfully updated."
      redirect_to transfer_url(@transfer)
    else
      render "edit"
    end
  end

  def destroy
    @transfer = Transfer.find(params[:id])
    if @transfer.destroy
      flash[:notice] = "Transfer was successfully deleted."
      redirect_to transfers_url
    end
  end

end

app/helpers/transfers_helper.rb
module TransfersHelper
  def display_type(type)
    rs = case type
      when Transfer::TYPE[:incoming] then return "Ulazni"
      when Transfer::TYPE[:outgoing] then return "Izlazni"
    end
    return rs
  end
end

app/views/transfers/_form.html.erb
<div> 
  Tip: <%= f.select :in_out, {"Ulazni" => Transfer::TYPE[:incoming], "Izlazni" => Transfer::TYPE[:incoming]}%> 
</div>

<div>
  Iznos:<br/>
  <%= f.text_field :amount %>
</div>

<div>
  Datum:<br/>
  <%= f.date_select :date , :order => [:day, :month, :year], :start_year => 2000  %>
</div>

<div>
  Svrha:<br/>
  <%= f.text_area :purpose, :rows => 10 , :cols=> 20 %>
</div>

<div>Crno? | <%= f.check_box :is_secret %></div>

<div><%= f.hidden_field :member_id, :value => session[:user_id] %></div>

app/views/transfers/_index_menu.html.erb
<%= link_to 'Index', transfers_url %> | 
<%= link_to 'New', new_transfer_url %> | 
<%= link_to 'Search', search_transfers_url %>

app/views/transfers/_show_menu.html.erb
<%= link_to 'Index', transfers_url %> |
<%= link_to 'Info', transfer_url(@transfer) %> | 
<%= link_to 'Edit', edit_transfer_url(@transfer) %> |
<%= link_to 'Destroy', transfer_url(@transfer), :method => :delete, :confirm => "Are you sure?" %>

app/views/transfers/_sub_menu.html.erb
<%= link_to 'All', transfers_url %> | 
<%= link_to 'Secret', secret_transfers_url %> |
<%= link_to 'Incoming', incoming_transfers_url %> | 
<%= link_to 'Outgoing', outgoing_transfers_url %>

app/views/transfers/edit.html.erb
<% content_for :head do %> 
<%= render :partial => "show_menu" %>
<% end %>

<%= error_messages_for :transfer %>

<%= form_for @transfer do |f| %>

<%= render_form('form', f) %>

<p><%= f.submit 'Update' %></p>

<% end %>

app/views/transfers/index.html.erb
<% content_for :head do %> 
<%= render :partial => "index_menu" %> : <%= render :partial => "sub_menu" %>
<% end %>

<% unless @transfers.empty? %>

<p>
<table border='1'>
<tr>
<th>Iznos</th>
<th>Unio</th>
</tr>

<% for t in @transfers %>
<tr>
<td><%= link_to t.amount, transfer_url(t) %></td>
<td><%=h "#{t.member.last_name} #{t.member.first_name}"  if t.member %></td>
</tr>
<% end %>
</table>
</p>

<% end %>

app/views/transfers/new.html.erb
<% content_for :head do %> 
<%= render :partial => "index_menu" %>
<% end %>

<%= error_messages_for :transfer %>

<%= form_for @transfer do |f| %>

<%= render_form('form', f) %>

<p><%= f.submit 'Create' %></p>

<% end %>

app/views/transfers/search.html.erb
<% content_for :head do %> 
  <%= render :partial => "index_menu" %>
<% end %>

<%= form_tag search_transfers_path do %>
  <div>
    Purpose..<br/>
    <%= text_field_tag 'keyword' %>
    <%= submit_tag "Search" %>
  </div>
<% end %>


<% unless @transfers.empty? %>
  <div>
    <ul>

      <% for t in @transfers %>
        <li><%= link_to t.amount, transfer_url(t) %></li>
      <% end %>

    </ul>
  </div>
<% end %>

app/views/transfers/show.html.erb
<% content_for :head do %> 
<%= render :partial => "show_menu" %>
<% end %>

<p>
Iznos: <%= @transfer.amount %> kuna
</p>

<p>
Datum: <%= @transfer.date %>
</p>

<p>
Svrha:<br/>
<%= @transfer.purpose %>
</p>

<p>
Unjeo: <%= "#{@transfer.member.first_name} #{@transfer.member.last_name}" %>
</p>